#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,5.2,9
#
M3_V2.0.xem3: package/cfg/M3_V2.0.xem3.mak

clean::
	-$(RM) package/cfg/M3_V2.0.xem3.mak
